# Image tags for GitOps - ArgoCD watches these values - testing
image:
  frontend:
    repository: urchytech/3-tier-deployment_frontend
    tag: 9fda5261a543a7c6b979cb27e027b7a149a37e37
  backend:
    repository: urchytech/3-tier-deployment_backend
    tag: 9fda5261a543a7c6b979cb27e027b7a149a37e37
